### PR TITLE
Add godocs and Documentation.md

### PR DESCRIPTION
**Pull request by hectorj2f**
This PR adds some documentation in the source code and a section `docs` with additional information on how to use `fleemmer`.

ping @htr

### CODE REVIEW

**Comment by htr** [comment]
LGTM. I should be able to give you a WFM in some hours.

**Comment by hectorj2f** [comment]
ping @puja108  @htr

**Comment by puja108** [comment]
looks good, would have some language edits, should I do them myself and commit to the PR?

**Comment by hectorj2f** [comment]
@puja all yours 👍

**Comment by puja108** [comment]
done, all good from my side

**Comment by hectorj2f** [comment]
@htr I'll merge this PR, I tested and it works :)

**Pull request merged**
