### PR TITLE
fix typos in documents and comments

### PR DESCRIPTION
**Pull request by dongsupark**
- Change the old name `"fleemer"` to the new name `"nomi"`.
- Fix a wrong example with `"--generate-plots"` to `"--generate-gnuplots"`, also from `192.68.*` to `192.168.*`.

### CODE REVIEW

**Comment by hectorj2f** [comment]
Thx @dongsupark, LGTM. I will merge it.

**Comment by dongsupark** [comment]
@hectorj2f You're so fast! :-) I just updated the branch again..

**Comment by hectorj2f** [comment]
@dongsupark Please, rebase to get the latest changes. Tests should be fixed by now 👍

**Comment by dongsupark** [comment]
@hectorj2f Rebased. Thanks!

**Comment by hectorj2f** [comment]
LGTM. Thanks for your contribution @dongsupark

**Pull request merged**
